import Navigation from "../Components/Navigation";
import Footer from "../Components/Footer";
import StyledJsxRegistry from "./registry";
import { Space_Grotesk } from "@next/font/google";
import "../styles/globals.css";

const font = Space_Grotesk({
    weight: "400",
    subsets: ["latin"],
    variable: "--fuente",
});

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>Duck IO</title>
            </head>
            <body className={font.className}>
                <Navigation />
                <main>
                    <StyledJsxRegistry>{children}</StyledJsxRegistry>
                </main>
                <Footer />
            </body>
        </html>
    );
}
